CircleCI Commit

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -6,18 +6,27 @@ jobs:
       - image: cimg/openjdk:17.0
     steps:
       - checkout
+      # Run Maven tests
       - run:
           name: "Run Maven tests"
           command: mvn clean test
+      # Push to main branch if tests pass
       - run:
-          name: "Push to main if tests pass"
+          name: "Merge circleci-project-setup into main and push"
           command: |
-            git config --global user.email "circleci@example.com"
-            git config --global user.name "CircleCI"
-            git remote set-url origin https://$GH_TOKEN@github.com/username/repo.git
+            git config --global user.email "jolethetrole@gmail.com"
+            git config --global user.name "joelshrestha-dev"
+            git remote set-url origin https://$GH_TOKEN@github.com/joelshrestha-dev/Travis412.git
             git checkout main
-            git merge $CIRCLE_BRANCH
+            git merge circleci-project-setup
             git push origin main
+      # Notify via email if tests fail
+      - run:
+          name: "Notify if tests fail"
+          command: |
+            if [ $? -ne 0 ]; then
+              echo "CircleCI Build Failed" | mail -s "CircleCI Build Failed" jolethetrole@gmail.com
+            fi
 
 workflows:
   build-and-deploy:
